# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.api.monitor_api import MonitorApi  # noqa: E501
from uptrends.rest import ApiException


class TestMonitorApi(unittest.TestCase):
    """MonitorApi unit test stubs"""

    def setUp(self):
        self.api = uptrends.api.monitor_api.MonitorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_monitor_cleanup_maintenance_periods(self):
        """Test case for monitor_cleanup_maintenance_periods

        Clears out all one-time maintenance periods for the specified monitor older than the specified date  # noqa: E501
        """
        pass

    def test_monitor_clone_monitor(self):
        """Test case for monitor_clone_monitor

        Creates a clone (duplicate) of the specified monitor.  # noqa: E501
        """
        pass

    def test_monitor_create_maintenance_period_for_monitor(self):
        """Test case for monitor_create_maintenance_period_for_monitor

        Saves the new maintenance period provided for the specified monitor  # noqa: E501
        """
        pass

    def test_monitor_delete_maintenance_period_from_monitor(self):
        """Test case for monitor_delete_maintenance_period_from_monitor

        Deletes the specified maintenance period from the specified monitor  # noqa: E501
        """
        pass

    def test_monitor_delete_monitor(self):
        """Test case for monitor_delete_monitor

        Deletes the specified monitor.  # noqa: E501
        """
        pass

    def test_monitor_get_all_maintenance_periods_for_monitor(self):
        """Test case for monitor_get_all_maintenance_periods_for_monitor

        Finds all maintenance periods for a monitor.  # noqa: E501
        """
        pass

    def test_monitor_get_monitor(self):
        """Test case for monitor_get_monitor

        Returns the definition of the specified monitor.   # noqa: E501
        """
        pass

    def test_monitor_get_monitors(self):
        """Test case for monitor_get_monitors

        Returns the definition of all monitors available in the account.  # noqa: E501
        """
        pass

    def test_monitor_patch_monitor(self):
        """Test case for monitor_patch_monitor

        Partially updates the definition of the specified monitor.  # noqa: E501
        """
        pass

    def test_monitor_post_monitor(self):
        """Test case for monitor_post_monitor

        Creates a new monitor.  # noqa: E501
        """
        pass

    def test_monitor_put_monitor(self):
        """Test case for monitor_put_monitor

        Updates the definition of the specified monitor.  # noqa: E501
        """
        pass

    def test_monitor_update_maintenance_period_for_monitor(self):
        """Test case for monitor_update_maintenance_period_for_monitor

        Updates the specified maintenance schedule for the specified monitor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
