# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.api.operator_api import OperatorApi  # noqa: E501
from uptrends.rest import ApiException


class TestOperatorApi(unittest.TestCase):
    """OperatorApi unit test stubs"""

    def setUp(self):
        self.api = uptrends.api.operator_api.OperatorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_operator_add_duty_period_for_operator(self):
        """Test case for operator_add_duty_period_for_operator

        Adds a duty schedule to the specified operator.  # noqa: E501
        """
        pass

    def test_operator_create_operator(self):
        """Test case for operator_create_operator

        Creates a new operator.  # noqa: E501
        """
        pass

    def test_operator_delete_authorization_for_operator(self):
        """Test case for operator_delete_authorization_for_operator

        Removes the specified authorization of this operator.  # noqa: E501
        """
        pass

    def test_operator_delete_duty_schedule_from_operator(self):
        """Test case for operator_delete_duty_schedule_from_operator

        Deletes the specified duty schedule of the specified operator.  # noqa: E501
        """
        pass

    def test_operator_delete_operator(self):
        """Test case for operator_delete_operator

        Deletes an existing operator.  # noqa: E501
        """
        pass

    def test_operator_get_all_operators(self):
        """Test case for operator_get_all_operators

        Gets a list of all operators.  # noqa: E501
        """
        pass

    def test_operator_get_authorizations_for_operator(self):
        """Test case for operator_get_authorizations_for_operator

        Gets all authorizations for the specified operator.  # noqa: E501
        """
        pass

    def test_operator_get_duty_schedule_for_operator(self):
        """Test case for operator_get_duty_schedule_for_operator

        Gets the duty schedules for an specified operator.  # noqa: E501
        """
        pass

    def test_operator_get_operator(self):
        """Test case for operator_get_operator

        Gets the details of the operator with the provided OperatorGuid.  # noqa: E501
        """
        pass

    def test_operator_get_operator_groups_for_operator(self):
        """Test case for operator_get_operator_groups_for_operator

        Gets a list of all operator groups for the specified operator.  # noqa: E501
        """
        pass

    def test_operator_post_authorization_for_operator(self):
        """Test case for operator_post_authorization_for_operator

        Assigns the specified authorization to this operator.  # noqa: E501
        """
        pass

    def test_operator_update_duty_period_for_operator(self):
        """Test case for operator_update_duty_period_for_operator

        Updates the specified duty schedule of the specified operator.  # noqa: E501
        """
        pass

    def test_operator_update_operator(self):
        """Test case for operator_update_operator

        Updates an existing operator.  # noqa: E501
        """
        pass

    def test_operator_update_operator_with_patch(self):
        """Test case for operator_update_operator_with_patch

        Updates an existing operator.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
