# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.api.statistics_api import StatisticsApi  # noqa: E501
from uptrends.rest import ApiException


class TestStatisticsApi(unittest.TestCase):
    """StatisticsApi unit test stubs"""

    def setUp(self):
        self.api = uptrends.api.statistics_api.StatisticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_statistics_get_monitor_group_statistics(self):
        """Test case for statistics_get_monitor_group_statistics

        Gets the monitor group statistics.  # noqa: E501
        """
        pass

    def test_statistics_get_monitor_statistics(self):
        """Test case for statistics_get_monitor_statistics

        Gets the monitor statistics.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
