# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.api.public_status_page_api import PublicStatusPageApi  # noqa: E501
from uptrends.rest import ApiException


class TestPublicStatusPageApi(unittest.TestCase):
    """PublicStatusPageApi unit test stubs"""

    def setUp(self):
        self.api = uptrends.api.public_status_page_api.PublicStatusPageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_public_status_page_add_authorization_to_public_status_page(self):
        """Test case for public_status_page_add_authorization_to_public_status_page

        Creates a new authorization for the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_delete_public_status_page(self):
        """Test case for public_status_page_delete_public_status_page

        Deletes the definition of the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_get_authorizations_for_public_status_page(self):
        """Test case for public_status_page_get_authorizations_for_public_status_page

        Returns all authorizations for the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_get_public_status_page(self):
        """Test case for public_status_page_get_public_status_page

        Returns the definition of the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_get_public_status_pages(self):
        """Test case for public_status_page_get_public_status_pages

        Returns the definition of all public status pages available in the account.  # noqa: E501
        """
        pass

    def test_public_status_page_patch_public_status_page(self):
        """Test case for public_status_page_patch_public_status_page

        Partially updates the definition of the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_post_public_status_page(self):
        """Test case for public_status_page_post_public_status_page

        Creates a new public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_put_public_status_page(self):
        """Test case for public_status_page_put_public_status_page

        Updates the definition of the specified public status page.  # noqa: E501
        """
        pass

    def test_public_status_page_remove_authorization_from_public_status_page(self):
        """Test case for public_status_page_remove_authorization_from_public_status_page

        Removes an authorization from a public status page.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
