# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.models.vault_section import VaultSection  # noqa: E501
from uptrends.rest import ApiException


class TestVaultSection(unittest.TestCase):
    """VaultSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVaultSection(self):
        """Test VaultSection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uptrends.models.vault_section.VaultSection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
