# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uptrends
from uptrends.api.alert_definition_api import AlertDefinitionApi  # noqa: E501
from uptrends.rest import ApiException


class TestAlertDefinitionApi(unittest.TestCase):
    """AlertDefinitionApi unit test stubs"""

    def setUp(self):
        self.api = uptrends.api.alert_definition_api.AlertDefinitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alert_definition_add_monitor_group_to_alert_definition(self):
        """Test case for alert_definition_add_monitor_group_to_alert_definition

        Adds a monitor group to the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_add_monitor_to_alert_definition(self):
        """Test case for alert_definition_add_monitor_to_alert_definition

        Adds a monitor to the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_add_operator_group_to_escalation_level(self):
        """Test case for alert_definition_add_operator_group_to_escalation_level

        Adds an operator group to the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_add_operator_to_escalation_level(self):
        """Test case for alert_definition_add_operator_to_escalation_level

        Adds an operator to the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_create_alert_definition(self):
        """Test case for alert_definition_create_alert_definition

        Creates a new alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_delete_alert_definition(self):
        """Test case for alert_definition_delete_alert_definition

        Deletes an existing alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_get_all_alert_definitions(self):
        """Test case for alert_definition_get_all_alert_definitions

        Gets a list of all alert definitions.  # noqa: E501
        """
        pass

    def test_alert_definition_get_all_members(self):
        """Test case for alert_definition_get_all_members

        Gets a list of all monitor and monitor group guids of the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_get_escalation_level(self):
        """Test case for alert_definition_get_escalation_level

        Gets the escalation level information of the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_get_escalation_level_integration(self):
        """Test case for alert_definition_get_escalation_level_integration

        Gets the integrations for the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_get_escalation_level_operator(self):
        """Test case for alert_definition_get_escalation_level_operator

        Gets the operator and operator group guids for the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_get_specified_alert_definitions(self):
        """Test case for alert_definition_get_specified_alert_definitions

        Gets the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_patch_alert_definition(self):
        """Test case for alert_definition_patch_alert_definition

        Partially updates the definition of the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_put_alert_definition(self):
        """Test case for alert_definition_put_alert_definition

        Updates the definition of the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_remove_monitor_from_alert_definition(self):
        """Test case for alert_definition_remove_monitor_from_alert_definition

        Removes a monitor for the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_remove_monitor_group_from_alert_definition(self):
        """Test case for alert_definition_remove_monitor_group_from_alert_definition

        Removes a monitor group for the specified alert definition.  # noqa: E501
        """
        pass

    def test_alert_definition_remove_operator_from_escalation_level(self):
        """Test case for alert_definition_remove_operator_from_escalation_level

        Removes an operator for the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_remove_operator_group_from_escalation_level(self):
        """Test case for alert_definition_remove_operator_group_from_escalation_level

        Removes an operator group for the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_update_integration_for_escalation_with_patch(self):
        """Test case for alert_definition_update_integration_for_escalation_with_patch

        Partially updates an integration to the specified escalation level.  # noqa: E501
        """
        pass

    def test_alert_definition_update_integration_for_escalation_with_put(self):
        """Test case for alert_definition_update_integration_for_escalation_with_put

        Updates an integration for the specified escalation level.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
