# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AlertDefinitionOperator(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alert_definition': 'str',
        'escalationlevel': 'int',
        'operator': 'str'
    }

    attribute_map = {
        'alert_definition': 'AlertDefinition',
        'escalationlevel': 'Escalationlevel',
        'operator': 'Operator'
    }

    def __init__(self, alert_definition=None, escalationlevel=None, operator=None):  # noqa: E501
        """AlertDefinitionOperator - a model defined in Swagger"""  # noqa: E501

        self._alert_definition = None
        self._escalationlevel = None
        self._operator = None
        self.discriminator = None

        self.alert_definition = alert_definition
        self.escalationlevel = escalationlevel
        self.operator = operator

    @property
    def alert_definition(self):
        """Gets the alert_definition of this AlertDefinitionOperator.  # noqa: E501


        :return: The alert_definition of this AlertDefinitionOperator.  # noqa: E501
        :rtype: str
        """
        return self._alert_definition

    @alert_definition.setter
    def alert_definition(self, alert_definition):
        """Sets the alert_definition of this AlertDefinitionOperator.


        :param alert_definition: The alert_definition of this AlertDefinitionOperator.  # noqa: E501
        :type: str
        """
        if alert_definition is None:
            raise ValueError("Invalid value for `alert_definition`, must not be `None`")  # noqa: E501

        self._alert_definition = alert_definition

    @property
    def escalationlevel(self):
        """Gets the escalationlevel of this AlertDefinitionOperator.  # noqa: E501


        :return: The escalationlevel of this AlertDefinitionOperator.  # noqa: E501
        :rtype: int
        """
        return self._escalationlevel

    @escalationlevel.setter
    def escalationlevel(self, escalationlevel):
        """Sets the escalationlevel of this AlertDefinitionOperator.


        :param escalationlevel: The escalationlevel of this AlertDefinitionOperator.  # noqa: E501
        :type: int
        """
        if escalationlevel is None:
            raise ValueError("Invalid value for `escalationlevel`, must not be `None`")  # noqa: E501

        self._escalationlevel = escalationlevel

    @property
    def operator(self):
        """Gets the operator of this AlertDefinitionOperator.  # noqa: E501


        :return: The operator of this AlertDefinitionOperator.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this AlertDefinitionOperator.


        :param operator: The operator of this AlertDefinitionOperator.  # noqa: E501
        :type: str
        """
        if operator is None:
            raise ValueError("Invalid value for `operator`, must not be `None`")  # noqa: E501

        self._operator = operator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertDefinitionOperator, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertDefinitionOperator):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
