# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CheckpointRegion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'child_regions': 'list[int]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'child_regions': 'ChildRegions'
    }

    def __init__(self, id=None, name=None, child_regions=None):  # noqa: E501
        """CheckpointRegion - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._child_regions = None
        self.discriminator = None

        self.id = id
        if name is not None:
            self.name = name
        if child_regions is not None:
            self.child_regions = child_regions

    @property
    def id(self):
        """Gets the id of this CheckpointRegion.  # noqa: E501


        :return: The id of this CheckpointRegion.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CheckpointRegion.


        :param id: The id of this CheckpointRegion.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this CheckpointRegion.  # noqa: E501


        :return: The name of this CheckpointRegion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CheckpointRegion.


        :param name: The name of this CheckpointRegion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def child_regions(self):
        """Gets the child_regions of this CheckpointRegion.  # noqa: E501


        :return: The child_regions of this CheckpointRegion.  # noqa: E501
        :rtype: list[int]
        """
        return self._child_regions

    @child_regions.setter
    def child_regions(self, child_regions):
        """Sets the child_regions of this CheckpointRegion.


        :param child_regions: The child_regions of this CheckpointRegion.  # noqa: E501
        :type: list[int]
        """

        self._child_regions = child_regions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckpointRegion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckpointRegion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
