# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DateTimePatternMatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offset_utc': 'int',
        'max_difference': 'int'
    }

    attribute_map = {
        'offset_utc': 'OffsetUTC',
        'max_difference': 'MaxDifference'
    }

    def __init__(self, offset_utc=None, max_difference=None):  # noqa: E501
        """DateTimePatternMatch - a model defined in Swagger"""  # noqa: E501

        self._offset_utc = None
        self._max_difference = None
        self.discriminator = None

        self.offset_utc = offset_utc
        self.max_difference = max_difference

    @property
    def offset_utc(self):
        """Gets the offset_utc of this DateTimePatternMatch.  # noqa: E501


        :return: The offset_utc of this DateTimePatternMatch.  # noqa: E501
        :rtype: int
        """
        return self._offset_utc

    @offset_utc.setter
    def offset_utc(self, offset_utc):
        """Sets the offset_utc of this DateTimePatternMatch.


        :param offset_utc: The offset_utc of this DateTimePatternMatch.  # noqa: E501
        :type: int
        """
        if offset_utc is None:
            raise ValueError("Invalid value for `offset_utc`, must not be `None`")  # noqa: E501

        self._offset_utc = offset_utc

    @property
    def max_difference(self):
        """Gets the max_difference of this DateTimePatternMatch.  # noqa: E501


        :return: The max_difference of this DateTimePatternMatch.  # noqa: E501
        :rtype: int
        """
        return self._max_difference

    @max_difference.setter
    def max_difference(self, max_difference):
        """Sets the max_difference of this DateTimePatternMatch.


        :param max_difference: The max_difference of this DateTimePatternMatch.  # noqa: E501
        :type: int
        """
        if max_difference is None:
            raise ValueError("Invalid value for `max_difference`, must not be `None`")  # noqa: E501

        self._max_difference = max_difference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DateTimePatternMatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DateTimePatternMatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
