# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LinksData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'next': 'str',
        '_self': 'str'
    }

    attribute_map = {
        'next': 'Next',
        '_self': 'Self'
    }

    def __init__(self, next=None, _self=None):  # noqa: E501
        """LinksData - a model defined in Swagger"""  # noqa: E501

        self._next = None
        self.__self = None
        self.discriminator = None

        if next is not None:
            self.next = next
        if _self is not None:
            self._self = _self

    @property
    def next(self):
        """Gets the next of this LinksData.  # noqa: E501

        Url for next data set  # noqa: E501

        :return: The next of this LinksData.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this LinksData.

        Url for next data set  # noqa: E501

        :param next: The next of this LinksData.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def _self(self):
        """Gets the _self of this LinksData.  # noqa: E501

        Url for this data set (data might get updated, depending on your parameters)  # noqa: E501

        :return: The _self of this LinksData.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this LinksData.

        Url for this data set (data might get updated, depending on your parameters)  # noqa: E501

        :param _self: The _self of this LinksData.  # noqa: E501
        :type: str
        """

        self.__self = _self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinksData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinksData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
