# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OperatorGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operator_group_guid': 'str',
        'description': 'str',
        'is_everyone': 'bool',
        'is_administrators_group': 'bool'
    }

    attribute_map = {
        'operator_group_guid': 'OperatorGroupGuid',
        'description': 'Description',
        'is_everyone': 'IsEveryone',
        'is_administrators_group': 'IsAdministratorsGroup'
    }

    def __init__(self, operator_group_guid=None, description=None, is_everyone=None, is_administrators_group=None):  # noqa: E501
        """OperatorGroup - a model defined in Swagger"""  # noqa: E501

        self._operator_group_guid = None
        self._description = None
        self._is_everyone = None
        self._is_administrators_group = None
        self.discriminator = None

        self.operator_group_guid = operator_group_guid
        if description is not None:
            self.description = description
        if is_everyone is not None:
            self.is_everyone = is_everyone
        if is_administrators_group is not None:
            self.is_administrators_group = is_administrators_group

    @property
    def operator_group_guid(self):
        """Gets the operator_group_guid of this OperatorGroup.  # noqa: E501

        The unique identifier of this Operator group  # noqa: E501

        :return: The operator_group_guid of this OperatorGroup.  # noqa: E501
        :rtype: str
        """
        return self._operator_group_guid

    @operator_group_guid.setter
    def operator_group_guid(self, operator_group_guid):
        """Sets the operator_group_guid of this OperatorGroup.

        The unique identifier of this Operator group  # noqa: E501

        :param operator_group_guid: The operator_group_guid of this OperatorGroup.  # noqa: E501
        :type: str
        """
        if operator_group_guid is None:
            raise ValueError("Invalid value for `operator_group_guid`, must not be `None`")  # noqa: E501

        self._operator_group_guid = operator_group_guid

    @property
    def description(self):
        """Gets the description of this OperatorGroup.  # noqa: E501

        The descriptive name of this operator group  # noqa: E501

        :return: The description of this OperatorGroup.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OperatorGroup.

        The descriptive name of this operator group  # noqa: E501

        :param description: The description of this OperatorGroup.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_everyone(self):
        """Gets the is_everyone of this OperatorGroup.  # noqa: E501

        Indicates whether this is the default group for all operators  # noqa: E501

        :return: The is_everyone of this OperatorGroup.  # noqa: E501
        :rtype: bool
        """
        return self._is_everyone

    @is_everyone.setter
    def is_everyone(self, is_everyone):
        """Sets the is_everyone of this OperatorGroup.

        Indicates whether this is the default group for all operators  # noqa: E501

        :param is_everyone: The is_everyone of this OperatorGroup.  # noqa: E501
        :type: bool
        """

        self._is_everyone = is_everyone

    @property
    def is_administrators_group(self):
        """Gets the is_administrators_group of this OperatorGroup.  # noqa: E501


        :return: The is_administrators_group of this OperatorGroup.  # noqa: E501
        :rtype: bool
        """
        return self._is_administrators_group

    @is_administrators_group.setter
    def is_administrators_group(self, is_administrators_group):
        """Sets the is_administrators_group of this OperatorGroup.


        :param is_administrators_group: The is_administrators_group of this OperatorGroup.  # noqa: E501
        :type: bool
        """

        self._is_administrators_group = is_administrators_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperatorGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperatorGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
