# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PresetPeriodTypeWithExclusive(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    CURRENTDAY = "CurrentDay"
    CURRENTWEEK = "CurrentWeek"
    CURRENTMONTH = "CurrentMonth"
    CURRENTYEAR = "CurrentYear"
    PREVIOUSDAY = "PreviousDay"
    PREVIOUSWEEK = "PreviousWeek"
    PREVIOUSMONTH = "PreviousMonth"
    PREVIOUSYEAR = "PreviousYear"
    LAST24HOURS = "Last24Hours"
    LAST48HOURS = "Last48Hours"
    LAST7DAYS = "Last7Days"
    LAST30DAYS = "Last30Days"
    LAST60DAYS = "Last60Days"
    LAST90DAYS = "Last90Days"
    LAST365DAYS = "Last365Days"
    LAST3MONTHS = "Last3Months"
    LAST6MONTHS = "Last6Months"
    LAST12MONTHS = "Last12Months"
    LAST24MONTHS = "Last24Months"
    LAST24HOURSEXCL = "Last24HoursExcl"
    LAST48HOURSEXCL = "Last48HoursExcl"
    LAST7DAYSEXCL = "Last7DaysExcl"
    LAST30DAYSEXCL = "Last30DaysExcl"
    LAST60DAYSEXCL = "Last60DaysExcl"
    LAST90DAYSEXCL = "Last90DaysExcl"
    LAST365DAYSEXCL = "Last365DaysExcl"
    LAST3MONTHSEXCL = "Last3MonthsExcl"
    LAST6MONTHSEXCL = "Last6MonthsExcl"
    LAST12MONTHSEXCL = "Last12MonthsExcl"
    LAST24MONTHSEXCL = "Last24MonthsExcl"
    ALL = "All"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """PresetPeriodTypeWithExclusive - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PresetPeriodTypeWithExclusive, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PresetPeriodTypeWithExclusive):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
