# coding: utf-8

"""
    Uptrends API v4

    This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VaultSection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vault_section_guid': 'str',
        'name': 'str'
    }

    attribute_map = {
        'vault_section_guid': 'VaultSectionGuid',
        'name': 'Name'
    }

    def __init__(self, vault_section_guid=None, name=None):  # noqa: E501
        """VaultSection - a model defined in Swagger"""  # noqa: E501

        self._vault_section_guid = None
        self._name = None
        self.discriminator = None

        self.vault_section_guid = vault_section_guid
        if name is not None:
            self.name = name

    @property
    def vault_section_guid(self):
        """Gets the vault_section_guid of this VaultSection.  # noqa: E501

        The Guid of this vault section  # noqa: E501

        :return: The vault_section_guid of this VaultSection.  # noqa: E501
        :rtype: str
        """
        return self._vault_section_guid

    @vault_section_guid.setter
    def vault_section_guid(self, vault_section_guid):
        """Sets the vault_section_guid of this VaultSection.

        The Guid of this vault section  # noqa: E501

        :param vault_section_guid: The vault_section_guid of this VaultSection.  # noqa: E501
        :type: str
        """
        if vault_section_guid is None:
            raise ValueError("Invalid value for `vault_section_guid`, must not be `None`")  # noqa: E501

        self._vault_section_guid = vault_section_guid

    @property
    def name(self):
        """Gets the name of this VaultSection.  # noqa: E501

        The name for this vault section  # noqa: E501

        :return: The name of this VaultSection.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VaultSection.

        The name for this vault section  # noqa: E501

        :param name: The name of this VaultSection.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VaultSection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VaultSection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
